# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdzK8s < Formula
  desc "Kubernetes overview, debugging & admin TUI"
  homepage "https://github.com/ladec-iadvize/idz-k8s"
  version "3.7.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.7.3/idz-k8s_3.7.3_darwin_amd64.tar.gz"
      sha256 "4613c17f245435eccb6320d70817ef52d3e3b2c7b8aff17e492c27c2d38faba6"

      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.7.3/idz-k8s_3.7.3_darwin_arm64.tar.gz"
      sha256 "0323a719173f2bfa62067e9f97b3509d0a9199f609f6c56cd17814afba06cca8"

      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.7.3/idz-k8s_3.7.3_linux_amd64.tar.gz"
      sha256 "464b9fb4fe571b54617296fd055a2955ed6c159a873754263d97177253dec51d"
      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.7.3/idz-k8s_3.7.3_linux_arm64.tar.gz"
      sha256 "f5d84bfdda07d37b72f9849eedd24819bcff6754f33751fe8f08ad80fe3e4d1a"
      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
  end

  test do
    system "#{bin}/idz-k8s", "--version"
  end
end
