# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdzK8s < Formula
  desc "Kubernetes overview, debugging & admin TUI"
  homepage "https://github.com/ladec-iadvize/idz-k8s"
  version "3.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.10.0/idz-k8s_3.10.0_darwin_amd64.tar.gz"
      sha256 "15908d4f8d378a5f4bc951f985275a87b8f3675ea9c7496f15aba2c812086a36"

      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.10.0/idz-k8s_3.10.0_darwin_arm64.tar.gz"
      sha256 "e7ca37d73e38f7a1ac81060c02053ab3b6ec4830a1fb55141bb5e2871199660a"

      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.10.0/idz-k8s_3.10.0_linux_amd64.tar.gz"
      sha256 "6e9d4a4bf200f6a58c0ce16a2fd20f4a7713edceea03af1f18be56cc4a1c8ed3"
      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.10.0/idz-k8s_3.10.0_linux_arm64.tar.gz"
      sha256 "bcc517981d0a4d43d14e6163addcf84ee8a1a62e1e0146b0a689beb5f9f178e8"
      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
  end

  test do
    system "#{bin}/idz-k8s", "--version"
  end
end
