# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdzK8s < Formula
  desc "Kubernetes overview, debugging & admin TUI"
  homepage "https://github.com/ladec-iadvize/idz-k8s"
  version "3.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.1.0/idz-k8s_3.1.0_darwin_amd64.tar.gz"
      sha256 "70bf237b80a95b216d5ea196d563eafa4fa44ff1fabbbc3431a200f2e63ce313"

      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.1.0/idz-k8s_3.1.0_darwin_arm64.tar.gz"
      sha256 "15df5bf87afab7301e6a8220f805fe2d1415c77e5f2e7827f00976d1712f6ea0"

      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.1.0/idz-k8s_3.1.0_linux_amd64.tar.gz"
      sha256 "c7461919a9defaee1cbe059effa3fb71cf0e5318072ce9d23f1dbf2ed7830e58"
      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ladec-iadvize/idz-k8s/releases/download/v3.1.0/idz-k8s_3.1.0_linux_arm64.tar.gz"
      sha256 "7472318ef87bc9273da4739292c1f34f6e0c28c9e4bfb418aadae6680cce130b"
      define_method(:install) do
        bin.install "idz-k8s"
      end
    end
  end

  test do
    system "#{bin}/idz-k8s", "--version"
  end
end
